apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-bot-db
spec:
  selector:
    matchLabels:
      app: survey-bot-db
  template:
    metadata:
      labels:
        app: survey-bot-db
      annotations:
        k8up.io/backupcommand: su - root -c 'pg_dumpall -l postgres -h localhost -p 5432 -U postgres'
    spec:
      containers:
      - image: postgres:11
        name: survey-bot-db
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
      - name:  db-data
        persistentVolumeClaim:
          claimName: survey-bot-db-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: survey-bot-pg-exporter
  name: survey-bot-bot-pg-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: survey-bot-bot-pg-exporter
  template:
    metadata:
      labels:
        app: survey-bot-bot-pg-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9187"
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_URI
          value: survey-bot-db:5432/postgres?sslmode=disable
        - name: DATA_SOURCE_USER
          value: postgres
        - name: DATA_SOURCE_PASS
          value: postgres
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: survey-bot-db
        - name: PG_EXPORTER_INCLUDE_DATABASES
          value: postgres
        ports:
        - containerPort: 9187
        image: quay.io/prometheuscommunity/postgres-exporter:latest
        imagePullPolicy: Always
        name: survey-bot-bot-pg-exporter
      restartPolicy: Always
      terminationGracePeriodSeconds: 0