apiVersion: v1
kind: Service
metadata:
  name: survey-bot
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 7777
    name: metrics
    targetPort: 7777
  selector:
    app: survey-bot
---
apiVersion: v1
kind: Service
metadata:
  name: survey-bot-db
spec:
  ports:
  - port: 5432
  selector:
    app: survey-bot-db